### ISSUE TITLE
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by RanaTahirSohail** [techquest/isw-mobile-payment-sdk-android#5]
10-09 11:43:12.140 4361-4361/com.cybussolutions.ticketvalidator E/ViewRootImpl: sendUserActionEvent() mView == null
10-09 11:43:47.240 4361-5631/com.cybussolutions.ticketvalidator E/AndroidRuntime: FATAL EXCEPTION: Waiting to resend
    Process: com.cybussolutions.ticketvalidator, PID: 4361
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8251)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1344)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5433)
        at android.view.View.invalidateInternal(View.java:13980)
        at android.view.View.invalidate(View.java:13944)
        at android.view.View.invalidate(View.java:13928)
        at android.widget.TextView.checkForRelayout(TextView.java:8401)
        at android.widget.TextView.setText(TextView.java:5009)
        at android.widget.TextView.setText(TextView.java:4834)
        at android.widget.TextView.setText(TextView.java:4809)
        at com.interswitchng.iswmobilesdk.shared.fragments.IswOtpFragment$a.run(SourceFile:166)
        at java.util.Timer$TimerImpl.run(Timer.java:284)
10-09 11:43:47.420 4361-4361/com.cybussolutions.ticketvalidator E/ViewRootImpl: sendUserActionEvent() mView == null

**Comment by ebi-igweze** [comment]
Hello @RanaTahirSohail please update your version to the latest version of the sdk, [check here](https://github.com/techquest/isw-mobile-payment-sdk-android/tags)
